### ISSUE TITLE
sysdata module doesn't properly read k10temp sensor

### ISSUE THREAD

**Issue by kozross** [ultrabug/py3status#1354]
Offending line is here:

```m = re.search("(Core 0|CPU Temp).+\+(.+).+\(.+", sensors)```

This won't pick anything up from the output of ``k10-temp``, which looks something like this on my machine:

```[koz@Sebastian ~]$ sensors k10temp-pci-00c3
k10temp-pci-00c3
Adapter: PCI adapter
temp1:        +48.0°C  (high = +70.0°C)
```

Given that this is the default sensor for AMD CPUs, not picking this up seems a bit amiss. Indeed, on my machine, I have to run a custom script to parse ``sensors`` output myself. I would understand that defaulting to this behaviour if a zone is not provided is fine, but I provided the zone using the ``zone`` argument, and it still didn't help.

**Comment by lasers** [comment]
Duplicate https://github.com/ultrabug/py3status/issues/1315. You can try `lm_sensors`. It is a beast that ought to parse everything properly.

**Comment by kozross** [comment]
@lasers I couldn't find the name of such a module in the documentation at ReadTheDocs. Do I need to be checking a specific version?

**Comment by lasers** [comment]
I mentioned it in #1315. Here's the PR: https://github.com/ultrabug/py3status/pull/1294. For now, we will need `thresholds = []` in the config to disable `lm_sensors`'s `auto.input` coloring. You can fake coloring with static color `lime`.
```
lm_sensors {
    format_chip = '[\?if=name=k10temp-pci-00c3 CPU] {format_sensor}'
    format_sensor = '\?color=lime {input:g}°C'
    thresholds = []
}
```

**Comment by kozross** [comment]
So wait, this isn't part of mainline yet? OK, that makes more sense. I'm using a version provided by my system's package manager, so I guess I'll have to wait till it gets merged. If it gets merged.

**Comment by lasers** [comment]
Yes. Also, I do not know when it will get merged. It might be several months or years before it gets merged as I need `py3` to be able to get `thresholds` from modules, not just from users.

If you can, tell `py3status` to also include modules in different directory.
```
# i3 config
bar {
    status_command py3status --include ~/.config/py3status/modules 
}
```
and drop `lm_sensors` in `~/.config/py3status/modules/`.

**Comment by kozross** [comment]
I just tried that, and it works, except that instead of printing one temperature, it prints about a thousand of them and overstretches my bar.

**Comment by lasers** [comment]
Literally everything by default. Next, specify `chips` and/or `sensors` so you can follow the particular temperatures, voltages, fans, or whatever it is. If you need help with setting up the formats or such, I'll be here.

**Comment by kozross** [comment]
@lasers I used your configuration:

```
lm_sensors {
    format_chip = '[\?if=name=k10temp-pci-00c3 CPU] {format_sensor}'
    format_sensor = '\?color=lime {input:g}°C'
    thresholds = []
}
```

Did I misunderstand?

**Comment by lasers** [comment]
This works fine. However, if you output `sensors -u`, I can give you specific config as everybody have different hardware. I also want your `sensors -u` to improve `auto.input`.

**Comment by kozross** [comment]
As per request:

```
[koz@Sebastian ~]$ sensors -u
k10temp-pci-00c3
Adapter: PCI adapter
temp1:
  temp1_input: 30.000
  temp1_max: 70.000

it8655-isa-0290
Adapter: ISA adapter
in0:
  in0_input: 1.428
  in0_min: 0.000
  in0_max: 1.646
  in0_alarm: 0.000
  in0_beep: 0.000
in1:
  in1_input: 2.485
  in1_min: 0.000
  in1_max: 0.676
  in1_alarm: 1.000
  in1_beep: 0.000
in2:
  in2_input: 1.973
  in2_min: 2.769
  in2_max: 1.341
  in2_alarm: 1.000
  in2_beep: 0.000
in3:
  in3_input: 1.973
  in3_min: 1.679
  in3_max: 2.594
  in3_alarm: 0.000
  in3_beep: 0.000
in4:
  in4_input: 1.973
  in4_min: 2.692
  in4_max: 2.333
  in4_alarm: 1.000
  in4_beep: 0.000
in5:
  in5_input: 1.908
  in5_min: 0.600
  in5_max: 2.758
  in5_alarm: 0.000
  in5_beep: 0.000
in6:
  in6_input: 1.973
  in6_min: 0.948
  in6_max: 1.341
  in6_alarm: 1.000
  in6_beep: 0.000
3VSB:
  in7_input: 3.314
  in7_min: 2.529
  in7_max: 4.840
  in7_alarm: 0.000
  in7_beep: 0.000
Vbat:
  in8_input: 3.161
+3.3V:
  in9_input: 3.335
fan1:
  fan1_input: 701.000
  fan1_min: 41.000
  fan1_alarm: 0.000
  fan1_beep: 0.000
fan2:
  fan2_input: 0.000
  fan2_min: 10.000
  fan2_alarm: 1.000
  fan2_beep: 0.000
fan3:
  fan3_input: 736.000
  fan3_min: 12.000
  fan3_alarm: 0.000
  fan3_beep: 0.000
temp1:
  temp1_input: 30.000
  temp1_max: -71.000
  temp1_min: -15.000
  temp1_alarm: 1.000
  temp1_offset: 0.000
  temp1_beep: 0.000
temp2:
  temp2_input: 27.000
  temp2_max: -13.000
  temp2_min: -1.000
  temp2_alarm: 1.000
  temp2_type: 4.000
  temp2_offset: 0.000
  temp2_beep: 0.000
temp3:
  temp3_input: 28.000
  temp3_max: -74.000
  temp3_min: -20.000
  temp3_alarm: 1.000
  temp3_type: 4.000
  temp3_offset: 0.000
  temp3_beep: 0.000
intrusion0:
  intrusion0_alarm: 1.000
```
