### ISSUE TITLE
Cannot configure lm_sensors

### ISSUE THREAD

**Issue by Bysmyyr** [ultrabug/py3status#2042]
**Describe the bug**
I have tested several example configurations to lm_sensors and all looks same even they should not.

**Your py3status version**
py3status version 3.24 (python 3.9.2) on i3

**To Reproduce**
Steps to reproduce the behavior along with your py3status configuration (filter out any private values):

```
order += "lm_sensors"
lm_sensors {
        chips = ["coretemp-isa-0000"]
        sensors = ["package_id_0"]
        format = "{format_chip}"
        format_chip = "{format_sensor}"
        format_sensor = '[\?color=input {input}°C]'
        thresholds = [
        (0, "#5f00ff"),
        (20, "#00afff"),
        (40, "#d75f00"),
        (60, "#ff5f00"),
        (85, "#ff0000"),
   ]
        gradients = True
}

```
or any of the examples from documentation(or without).

shows always same too long output:
![image](https://user-images.githubusercontent.com/3306756/116029661-6ff0f400-a662-11eb-88e7-f95c1c322844.png)

plan is to show only that whole cpu temp and some else maybe but not all cores.
```
➜ sensors -u
ucsi_source_psy_USBC000:002-isa-0000
Adapter: ISA adapter
in0:
  in0_input: 0.000
  in0_min: 0.000
  in0_max: 0.000
curr1:
  curr1_input: 0.000
  curr1_max: 0.000

thinkpad-isa-0000
Adapter: ISA adapter
fan1:
  fan1_input: 3281.000
fan2:
  fan2_input: 3118.000
temp1:
  temp1_input: 51.000
temp2:
  temp2_input: 50.000
temp3:
  temp3_input: 64.000
temp4:
  temp4_input: 0.000
temp5:
  temp5_input: 69.000
temp6:
  temp6_input: 57.000
temp7:
  temp7_input: 60.000
temp8:
  temp8_input: 0.000
temp9:
  temp9_input: 0.000
temp10:
  temp10_input: 0.000
temp11:
  temp11_input: 1.000
temp12:
  temp12_input: 0.000
temp13:
  temp13_input: 0.000
temp14:
  temp14_input: 0.000
temp15:
  temp15_input: -125.000
temp16:
  temp16_input: 2.000

iwlwifi_1-virtual-0
Adapter: Virtual device
temp1:
  temp1_input: 44.000

nouveau-pci-0100
Adapter: PCI adapter
temp1:
  temp1_input: 43.000
  temp1_max: 95.000
  temp1_max_hyst: 3.000
  temp1_crit: 105.000
  temp1_crit_hyst: 5.000
  temp1_emergency: 135.000
  temp1_emergency_hyst: 5.000

BAT0-acpi-0
Adapter: ACPI interface
in0:
  in0_input: 17.437

coretemp-isa-0000
Adapter: ISA adapter
Package id 0:
  temp1_input: 52.000
  temp1_max: 100.000
  temp1_crit: 100.000
  temp1_crit_alarm: 0.000
Core 0:
  temp2_input: 51.000
  temp2_max: 100.000
  temp2_crit: 100.000
  temp2_crit_alarm: 0.000
Core 1:
  temp3_input: 52.000
  temp3_max: 100.000
  temp3_crit: 100.000
  temp3_crit_alarm: 0.000
Core 2:
  temp4_input: 47.000
  temp4_max: 100.000
  temp4_crit: 100.000
  temp4_crit_alarm: 0.000
Core 3:
  temp5_input: 48.000
  temp5_max: 100.000
  temp5_crit: 100.000
  temp5_crit_alarm: 0.000
Core 4:
  temp6_input: 49.000
  temp6_max: 100.000
  temp6_crit: 100.000
  temp6_crit_alarm: 0.000
Core 5:
  temp7_input: 49.000
  temp7_max: 100.000
  temp7_crit: 100.000
  temp7_crit_alarm: 0.000

ucsi_source_psy_USBC000:001-isa-0000
Adapter: ISA adapter
in0:
  in0_input: 0.000
  in0_min: 0.000
  in0_max: 0.000
curr1:
  curr1_input: 0.000
  curr1_max: 0.000

pch_cometlake-virtual-0
Adapter: Virtual device
temp1:
  temp1_input: 67.000

nvme-pci-5500
Adapter: PCI adapter
Composite:
  temp1_input: 46.850
  temp1_max: 83.850
  temp1_min: -5.150
  temp1_crit: 87.850
  temp1_alarm: 0.000

acpitz-acpi-0
Adapter: ACPI interface
temp1:
  temp1_input: 51.000
  temp1_crit: 128.000

```
